### ISSUE TITLE
maxWidth not working

### ISSUE THREAD

**Issue by cowboysdude** [morozgrafix/MMM-horoscope#2]
I put this in my config.js with odds results:

maxWidth: 200px, 
I also used plain numbers:
maxWidth: 200,
maxWidth: 20,

No matter what value I tried to assign the module would go 100% across the screen.

Would return to normal [400px] when the maxWidth was removed from config.js.

**Comment by morozgrafix** [comment]
have you tried to set it to `maxWidth: '200px',` (note single quotes around '200px', it need to be a string)?

It seems to work for me.
```
{
	module: 'MMM-horoscope',
	position: 'top_right', // This can be any of the regions.
	config: {
		// See ‘Configuration options’ for additional options and more information.
		sign: 'aries', // Zodiac sign
		maxWidth: '200px',
	}
},
```
![image](https://user-images.githubusercontent.com/1007608/30994359-73f10ad6-a468-11e7-973f-eb0550e31367.png)

**Comment by morozgrafix** [comment]
I'm going to close this one, feel free to reopen if you still have problems with it.
