### ISSUE TITLE
Recently broken...

### ISSUE THREAD

**Issue by pingywon** [morozgrafix/MMM-horoscope#7]
I have had MMM-horoscope running for over 2 years. I dont know what changed but it all of a sudden is broken. Any ideas or fixes? It seems rather dead around here...

**Comment by julien-vancouver** [comment]
Mine broke recently as well.

**Comment by 1batoora** [comment]
not working for me either

**Comment by pingywon** [comment]
I switched to MMM-Astrology. took some work, but I was able to get it working. Good luck!
